#!/bin/bash

#===================================================================================
#
#	FILE: test-outbound-web-connections.sh
#
#	USAGE: ---
#
#	DESCRIPTION: Performs a wget on each of the domains listed
#	in the ADDRESSES array below
#
#	OPTIONS: ---
#	REQUIREMENTS: ---
#	BUGS: ---
#	NOTES: ---
#	AUTHOR: PartFire LTD, hello@partfire.co.uk
#	COMPANY: PartFire LTD, LIVERPOOL, UK
#	VERSION: 1.0
#	CREATED: 05.07.2010 - 15:28:56
#	REVISION: ---
#===================================================================================


ADDRESSES=("partfire.co.uk" "google.com" "facebook.com" "github.com" "microsoft.com" )

# get array length
aLength=${#ADDRESSES[@]}

for (( i=0; i<${aLength}; i++));
do
        wget -q -O /tmp/index.${ADDRESSES[$i]} --tries=2 --timeout=3 ${ADDRESSES[$i]} &> /dev/null
        wait $!

        if [ ! -s /tmp/index.${ADDRESSES[$i]} ];then
                wget -q -O /tmp/index.${ADDRESSES[$i]} --tries=2 --timeout=3 https://${ADDRESSES[$i]} &> /dev/null
                wait $!
fi
done

for (( i=0; i<${aLength}; i++));
do
        if [ ! -s /tmp/index.${ADDRESSES[$i]} ];then
                echo ${ADDRESSES[$i]} " Failed"
        else
                echo ${ADDRESSES[$i]} " Success"
                rm -rf /tmp/index.${ADDRESSES[$i]}
fi

done
